/**
 * FLODE's own UI strings (German + English). Card texts and the dependency
 * map come from `@flode/ui-core`'s i18next files; everything else from Home Assistant.
 */
const STRINGS = {
  de: {
    title: 'FLODE',
    open: 'Öffnen',
    back: 'Zurück',
    save: 'Speichern',
    saved: 'Gespeichert',
    saving: 'Speichert …',
    unsaved: 'Ungespeichert',
    loading: 'Wird geladen …',
    delete: 'Löschen',
    fit: 'Alles zeigen',
    zoomIn: 'Vergrößern',
    zoomOut: 'Verkleinern',
    undo: 'Rückgängig',
    redo: 'Wiederholen',
    add: 'Baustein hinzufügen',
    on: 'An',
    off: 'Aus',
    never: 'Noch nie ausgelöst',
    empty: 'Keine Automation gefunden.',
    nodeConfig: 'Konfiguration',
    inspectorEmpty: 'Wähle einen Baustein auf der Canvas.',
    editYaml: 'In YAML bearbeiten',
    editUi: 'Im Formular bearbeiten',
    addHint: 'Öffnet HAs eigene Auswahl',
    newAutomation: 'Neue Automation',
    ioMore: 'Weitere Aktionen',
    ioYamlTitle: 'YAML einfügen',
    ioYamlIntro:
      'Füge eine Automation oder ein Skript als YAML ein (z. B. aus HAs YAML-Ansicht oder einem Forum). FLODE öffnet sie als Entwurf – gespeichert wird erst, wenn du speicherst.',
    ioOpenDraft: 'Als Entwurf öffnen',
    ioImportYaml: 'YAML einfügen …',
    ioImportJson: 'FLODE-Datei (JSON) importieren …',
    ioExportJson: 'Als FLODE-Datei (JSON) exportieren',
    ioCopyYaml: 'YAML kopieren',
    ioShowYaml: 'YAML anzeigen',
    importWarnTitle: 'FLODE hat nicht alles erkannt',
    importWarnText:
      'Beim Öffnen wurden Teile dieses Flows nicht erkannt. Prüfe ihn vor dem Speichern (⋮ → YAML anzeigen), damit nichts verloren geht:',
    yamlViewIntro: 'So schreibt FLODE diesen Flow beim Speichern in Home Assistant.',
    enableCard: 'Karte aktivieren',
    disableCard: 'Karte deaktivieren',
    disconnectCard: 'Verbindungen trennen',
    addHere: '{type} hier hinzufügen',
    ioYamlCopied: 'YAML in die Zwischenablage kopiert',
    ioSaveCopy: 'Als Kopie speichern …',
    shortcutsTitle: 'Tastenkürzel',
    minimap: 'Minimap',
    close: 'Schließen',
    shortcutsIntro: 'Im Editor – nicht während du in einem Feld tippst.',
    shortcutsGeneral: 'Allgemein',
    shortcutsEdit: 'Bearbeiten',
    shortcutsView: 'Ansicht',
    copyCard: 'Karte kopieren',
    pasteCard: 'Karte einfügen',
    duplicateCard: 'Karte duplizieren',
    toggleEnabledCard: 'Karte aktivieren/deaktivieren',
    deleteCard: 'Karte oder Verbindung löschen',
    cardCopied: 'Karte kopiert – {keys} fügt sie ein',
    ioCopyOf: 'Kopie von {name}',
    ioImported: 'Als Entwurf geöffnet – bitte prüfen und speichern',
    ioImportFailed: 'Import fehlgeschlagen:',
    mergeStart: 'Zusammenführen …',
    mergeHint:
      'Wähle zwei oder mehr Automationen, die zu einer neuen zusammengeführt werden. Die Originale bleiben unverändert.',
    mergeSelected: '{n} ausgewählt',
    mergeRun: 'Zusammenführen',
    mergeName: 'Zusammengeführt: {names}',
    mergeFailed: 'Zusammenführen fehlgeschlagen:',
    mergeDone: 'Zusammengeführt – als neue Automation offen. Die Originale bleiben unverändert.',
    manualTitle: 'Ab hier ausgeführt',
    manualRunning: 'Läuft …',
    manualDone: 'Durchgelaufen',
    manualNoChanges:
      'Keine Änderungen im Logbuch – die Geräte waren vermutlich schon in diesem Zustand.',
    manualLogbook: 'Was dabei passiert ist',
    manualLogbookEmpty:
      'Noch nichts im Logbuch – Home Assistant schreibt es mit ein paar Sekunden Verzögerung.',
    manualHint:
      'Von Hand gestartete Schritte speichert Home Assistant nicht als Ablauf (Trace) – FLODE zeigt sie hier, bis die Seite neu geladen wird.',
    runFrom: 'Ab hier ausführen',
    runFromTitle: 'Ab hier ausführen',
    runFromIntro:
      'Führt „{name}“ und alles danach jetzt echt in Home Assistant aus – Geräte werden wirklich geschaltet. Bedingungen werden mit den aktuellen Zuständen geprüft.',
    runFromPreparing: 'Wird vorbereitet …',
    runFromInvalid: 'Dieser Teil des Flows kann so nicht ausgeführt werden:',
    runFromStep: '{n} Schritt wird ausgeführt.',
    runFromSteps: '{n} Schritte werden ausgeführt.',
    runFromTriggerData:
      'Einige Schritte verwenden Daten des Auslösers (trigger.…). Die gibt es beim manuellen Start nicht – diese Schritte können fehlschlagen oder leere Werte nutzen.',
    runFromConfirm: 'Jetzt ausführen',
    runFromStarted: '„{name}“ läuft …',
    runFromDone: '„{name}“ und die folgenden Schritte sind durchgelaufen',
    runFromFailed: 'Ausführen fehlgeschlagen:',
    tplTitle: 'Template-Werkstatt',
    tplIntro:
      'Home Assistant rendert das Template live – mit Ergebnis-Typ und allem, worauf es reagiert.',
    tplRendering: 'Wird gerendert …',
    tplEmpty: '(leer)',
    tplUpdatesOn: 'Aktualisiert bei:',
    tplAllStates: 'jeder Zustandsänderung',
    tplTime: 'Zeit (jede Minute)',
    tplStatic: 'nichts – statisch',
    tplIdle: 'Schreib ein Template mit {{ … }} oder {% … %}.',
    tplResult: 'Ergebnis',
    tplVariables: 'Variablen',
    tplCopy: 'Kopieren',
    tplCopied: 'Template kopiert',
    tplSourceNone: 'Ohne',
    tplSourceGiven: 'Aus Ablauf-Schritt',
    tplSourceLastRun: 'Letzter Lauf',
    tplTestWithRun: 'Mit diesen Variablen Template testen',
    tplType_text: 'Text',
    tplType_number: 'Zahl',
    tplType_boolean: 'Ja/Nein',
    tplType_list: 'Liste',
    tplType_object: 'Objekt',
    tplType_none: 'Nichts',
    tplSnippet_state: 'Zustand',
    tplSnippet_number: 'Als Zahl',
    tplSnippet_isOn: 'Ist an?',
    tplSnippet_attribute: 'Attribut',
    tplSnippet_since: 'Seit wann',
    tplSnippet_countOn: 'Wie viele an',
    tplSnippet_trigger: 'Auslöser-Wert',
    tplSnippet_time: 'Uhrzeit',
    paletteTitle: 'Befehle',
    palettePlaceholder: 'Befehl, Baustein oder Automation suchen …',
    paletteNothing: 'Nichts gefunden',
    paletteCommands: 'Befehle',
    paletteAdd: 'Hinzufügen',
    paletteOpen: 'Öffnen',
    paletteHome: 'Zur Startseite',
    searchHint: 'Automation suchen …',
    searchPaletteHint: '{keys} für Befehle',
    assistButton: 'KI-Assistent',
    assistTitle: 'KI-Assistent',
    assistIntro:
      'Frag etwas zu dieser Automation oder gib eine Aufgabe – z. B. „Warum geht das Licht nachts nicht an?“ oder „Füge eine Benachrichtigung hinzu“. Änderungen schlägt die KI nur vor; übernommen wird erst mit deinem Klick.',
    assistIntroScript:
      'Frag etwas zu diesem Skript oder gib eine Aufgabe. Änderungen schlägt die KI nur vor; übernommen wird erst mit deinem Klick.',
    assistFindErrors: 'Fehler finden',
    assistFindErrorsPrompt:
      'Prüfe den Ablauf auf Fehler, Denkfehler und Randfälle (z. B. Neustart, nicht verfügbare Geräte, falsche Bedingungen). Liste gefundene Probleme mit kurzer Begründung auf. Schlage noch keine Änderung als YAML vor.',
    assistOptimize: 'Optimieren',
    assistOptimizePrompt:
      'Optimiere den Ablauf: robuster, einfacher und nach Home-Assistant-Best-Practices, ohne das Verhalten zu ändern. Erkläre kurz die Änderungen und gib die komplette neue Fassung.',
    assistExplain: 'Was macht das?',
    assistExplainPrompt: 'Erkläre in wenigen Sätzen, was dieser Ablauf macht und wann er auslöst.',
    assistPlaceholder: 'Frage oder Aufgabe (⌘↩ sendet)',
    assistSend: 'Senden',
    assistThinking: 'KI denkt nach …',
    assistClear: 'Gespräch leeren',
    assistProposal: 'Vorschlag: neue Fassung mit {n} Bausteinen',
    assistUnreadable: 'Der Vorschlag konnte nicht gelesen werden',
    assistUnknownEntity: 'Unbekannte Entität:',
    assistApply: 'Änderung übernehmen',
    assistApplied: 'Übernommen',
    assistAppliedToast: 'Änderung übernommen – ⌘Z macht sie rückgängig',
    assistPrivacy:
      'Die aktuelle Fassung und passende Entitäten gehen an die KI aus deinem Home Assistant. Gespeichert wird nichts ohne dich.',
    disabledGroup: 'Deaktiviert',
    aiButton: 'Mit KI erstellen',
    aiTitle: 'Mit KI erstellen',
    aiTitleScript: 'Skript mit KI erstellen',
    aiIntro:
      'Beschreibe, was passieren soll. Die KI aus deinem Home Assistant baut daraus einen Entwurf.',
    aiIntroScript:
      'Beschreibe, was das Skript tun soll. Die KI aus deinem Home Assistant baut daraus einen Entwurf.',
    aiDescribe: 'Beschreibung',
    aiExample1: 'Wenn nach Sonnenuntergang die Haustür aufgeht, Flurlicht für 5 Minuten an',
    aiExample2: 'Werktags um 6:30 Wohnzimmerlicht langsam hochdimmen',
    aiExample3: 'Benachrichtige mich, wenn die Waschmaschine fertig ist',
    aiExampleScript1:
      'Guten-Morgen-Skript: Licht mit wählbarer Helligkeit an, danach Rollläden hoch',
    aiExampleScript2: 'Alles aus: alle Lichter und Medien ausschalten, Haustür abschließen',
    aiExampleScript3: 'Timer-Skript: Kaffeemaschine für eine wählbare Anzahl Minuten einschalten',
    aiCreate: 'Entwurf erstellen',
    aiRunning: 'KI baut den Flow …',
    aiPrivacy:
      'Nur ein Entwurf – gespeichert wird erst, wenn du speicherst. Deine Beschreibung und Namen/IDs passender Entitäten gehen an die KI, die du in Home Assistant eingerichtet hast.',
    aiUnknown: 'Entwurf erstellt, aber diese Entitäten gibt es nicht: ',
    aiDone: 'Entwurf erstellt – bitte prüfen und dann speichern',
    aiSetupTitle: 'Automationen mit KI bauen',
    aiSetupText:
      'FLODE nutzt die KI, die du in Home Assistant einrichtest (eine Integration mit „AI Task“, z. B. OpenAI, Anthropic, Google oder Ollama). Danach unter Einstellungen → System → KI → „KI-Vorschläge“ → „Aufgaben zur Datengenerierung“ auswählen.',
    aiSetupDefault:
      'Du hast schon eine KI mit „AI Task“, aber keine als Standard für die Datengenerierung ausgewählt. Wähle sie unter Einstellungen → System → KI → „KI-Vorschläge“ aus.',
    aiOpenIntegrations: 'Geräte & Dienste öffnen',
    aiOpenDefault: 'KI auswählen',
    aiDismiss: 'Hinweis ausblenden',
    aiExplain: 'Lauf erklären',
    aiExplaining: 'KI liest den Lauf …',
    aiExplainAgain: 'Neu erklären',
    cancel: 'Abbrechen',
    runs: 'Abläufe',
    refresh: 'Neu laden',
    noRuns: 'Noch keine Abläufe – löse die Automation einmal aus.',
    runsHint: 'Home Assistant speichert pro Automation nur die letzten Abläufe (Standard: 5).',
    timeline: 'Zeitleiste',
    stepDetails: 'Schritt',
    pickStep: 'Klicke in der Zeitleiste auf einen Schritt, um seine Details zu sehen.',
    run_running: 'Läuft',
    run_finished: 'Erfolgreich',
    run_failed_conditions: 'Bedingung nicht erfüllt',
    run_error: 'Fehler',
    run_aborted: 'Abgebrochen',
    run_other: 'Beendet',
    lastRun: 'Letzter Lauf',
    showRuns: 'Abläufe anzeigen',
    addNext: 'Aktion hinzufügen (danach)',
    addFirstTrigger: 'Auslöser hinzufügen',
    addFirstAction: 'Aktion hinzufügen',
    emptyScriptHint: 'Was soll das Skript tun?',
    entry: 'Beginn',
    fields: 'Felder',
    emptyHint: 'Womit soll die Automation starten?',
    newScript: 'Neues Skript',
    automations: 'Automationen',
    scripts: 'Skripte',
    run: 'Ausführen (gespeicherte Version)',
    runNeedsSave: 'Erst speichern, dann ausführen',
    rename: 'Umbenennen',
    tabsLabel: 'Geöffnete Automationen',
    newTab: 'Neue Automation in neuem Tab',
    closeTab: 'Tab schließen',
    tidy: 'Aufräumen',
    tidied: 'Aufgeräumt – ⌘Z macht es rückgängig',
    mode: 'Modus',
    mode_single: 'Einzeln',
    mode_restart: 'Neustart',
    mode_queued: 'Warteschlange',
    mode_parallel: 'Parallel',
    resize: 'Breite ziehen · Doppelklick = Standard',
    homeHint:
      'Automationen und Skripte als Flow bauen, testen und verstehen – gespeichert wird ganz normales Home-Assistant-YAML.',
    loadFailed: 'Konnte nicht geladen werden',
    saveFailed: 'Speichern fehlgeschlagen',
    invalid: 'Ungültig',
    type_trigger: 'Auslöser',
    type_automation: 'Automation',
    type_script: 'Skript',
    type_condition: 'Bedingung',
    type_action: 'Aktion',
    type_delay: 'Verzögerung',
    type_wait: 'Warten',
    type_set_variables: 'Variablen',
  },
  en: {
    title: 'FLODE',
    open: 'Open',
    back: 'Back',
    save: 'Save',
    saved: 'Saved',
    saving: 'Saving …',
    unsaved: 'Unsaved',
    loading: 'Loading …',
    delete: 'Delete',
    fit: 'Fit view',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    undo: 'Undo',
    redo: 'Redo',
    add: 'Add block',
    on: 'On',
    off: 'Off',
    never: 'Never triggered',
    empty: 'No automation found.',
    nodeConfig: 'Configuration',
    inspectorEmpty: 'Select a block on the canvas.',
    editYaml: 'Edit in YAML',
    editUi: 'Edit in visual editor',
    addHint: "Opens HA's own picker",
    newAutomation: 'New automation',
    ioMore: 'More actions',
    ioYamlTitle: 'Paste YAML',
    ioYamlIntro:
      'Paste an automation or script as YAML (e.g. from HA’s YAML view or a forum). FLODE opens it as a draft – nothing is saved until you save.',
    ioOpenDraft: 'Open as draft',
    ioImportYaml: 'Paste YAML …',
    ioImportJson: 'Import FLODE file (JSON) …',
    ioExportJson: 'Export as FLODE file (JSON)',
    ioCopyYaml: 'Copy YAML',
    ioShowYaml: 'Show YAML',
    importWarnTitle: "FLODE didn't recognise everything",
    importWarnText:
      'Parts of this flow were not recognised when it was opened. Check it before saving (⋮ → Show YAML) so nothing gets lost:',
    yamlViewIntro: 'This is what FLODE writes to Home Assistant when you save this flow.',
    enableCard: 'Enable card',
    disableCard: 'Disable card',
    disconnectCard: 'Disconnect',
    addHere: 'Add {type} here',
    ioYamlCopied: 'YAML copied to the clipboard',
    ioSaveCopy: 'Save as copy …',
    shortcutsTitle: 'Keyboard shortcuts',
    minimap: 'Minimap',
    close: 'Close',
    shortcutsIntro: 'In the editor – not while you type in a field.',
    shortcutsGeneral: 'General',
    shortcutsEdit: 'Edit',
    shortcutsView: 'View',
    copyCard: 'Copy card',
    pasteCard: 'Paste card',
    duplicateCard: 'Duplicate card',
    toggleEnabledCard: 'Enable/disable card',
    deleteCard: 'Delete card or connection',
    cardCopied: 'Card copied – {keys} pastes it',
    ioCopyOf: 'Copy of {name}',
    ioImported: 'Opened as draft – review it, then save',
    ioImportFailed: 'Import failed:',
    mergeStart: 'Merge …',
    mergeHint:
      'Pick two or more automations to merge into a new one. The originals stay unchanged.',
    mergeSelected: '{n} selected',
    mergeRun: 'Merge',
    mergeName: 'Merged: {names}',
    mergeFailed: 'Merging failed:',
    mergeDone: 'Merged – open as a new automation. The originals stay unchanged.',
    manualTitle: 'Run from here',
    manualRunning: 'Running …',
    manualDone: 'Finished',
    manualNoChanges: 'No changes in the logbook – the devices were probably already in that state.',
    manualLogbook: 'What happened',
    manualLogbookEmpty:
      'Nothing in the logbook yet – Home Assistant writes it with a few seconds delay.',
    manualHint:
      'Home Assistant keeps no trace for steps started by hand – FLODE shows them here until the page reloads.',
    runFrom: 'Run from here',
    runFromTitle: 'Run from here',
    runFromIntro:
      'Runs “{name}” and everything after it for real in Home Assistant now – devices really switch. Conditions are checked against the current states.',
    runFromPreparing: 'Preparing …',
    runFromInvalid: 'This part of the flow can’t be run like this:',
    runFromStep: '{n} step will run.',
    runFromSteps: '{n} steps will run.',
    runFromTriggerData:
      'Some steps use trigger data (trigger.…). It doesn’t exist when starting by hand – those steps may fail or use empty values.',
    runFromConfirm: 'Run now',
    runFromStarted: '“{name}” is running …',
    runFromDone: '“{name}” and the following steps have finished',
    runFromFailed: 'Running failed:',
    tplTitle: 'Template workshop',
    tplIntro:
      'Home Assistant renders the template live – with the result type and everything it reacts to.',
    tplRendering: 'Rendering …',
    tplEmpty: '(empty)',
    tplUpdatesOn: 'Updates on:',
    tplAllStates: 'every state change',
    tplTime: 'time (every minute)',
    tplStatic: 'nothing – static',
    tplIdle: 'Write a template with {{ … }} or {% … %}.',
    tplResult: 'Result',
    tplVariables: 'Variables',
    tplCopy: 'Copy',
    tplCopied: 'Template copied',
    tplSourceNone: 'None',
    tplSourceGiven: 'From run step',
    tplSourceLastRun: 'Last run',
    tplTestWithRun: 'Test a template with these variables',
    tplType_text: 'Text',
    tplType_number: 'Number',
    tplType_boolean: 'Yes/No',
    tplType_list: 'List',
    tplType_object: 'Object',
    tplType_none: 'Nothing',
    tplSnippet_state: 'State',
    tplSnippet_number: 'As number',
    tplSnippet_isOn: 'Is on?',
    tplSnippet_attribute: 'Attribute',
    tplSnippet_since: 'Since when',
    tplSnippet_countOn: 'How many on',
    tplSnippet_trigger: 'Trigger value',
    tplSnippet_time: 'Time',
    paletteTitle: 'Commands',
    palettePlaceholder: 'Search commands, blocks or automations …',
    paletteNothing: 'Nothing found',
    paletteCommands: 'Commands',
    paletteAdd: 'Add',
    paletteOpen: 'Open',
    paletteHome: 'Go to start screen',
    searchHint: 'Search automations …',
    searchPaletteHint: '{keys} for commands',
    assistButton: 'AI assistant',
    assistTitle: 'AI assistant',
    assistIntro:
      'Ask about this automation or give it a task – e.g. “Why doesn’t the light turn on at night?” or “Add a notification”. The AI only proposes changes; nothing is applied until you click.',
    assistIntroScript:
      'Ask about this script or give it a task. The AI only proposes changes; nothing is applied until you click.',
    assistFindErrors: 'Find mistakes',
    assistFindErrorsPrompt:
      'Check the flow for mistakes, logic errors and edge cases (e.g. restarts, unavailable devices, wrong conditions). List the problems you find with a short reason. Do not propose YAML yet.',
    assistOptimize: 'Optimize',
    assistOptimizePrompt:
      'Optimize the flow: more robust, simpler and following Home Assistant best practices, without changing its behaviour. Briefly explain the changes and give the complete new version.',
    assistExplain: 'What does it do?',
    assistExplainPrompt: 'Explain in a few sentences what this flow does and when it runs.',
    assistPlaceholder: 'Question or task (⌘↩ sends)',
    assistSend: 'Send',
    assistThinking: 'AI is thinking …',
    assistClear: 'Clear conversation',
    assistProposal: 'Proposal: new version with {n} blocks',
    assistUnreadable: 'The proposal could not be read',
    assistUnknownEntity: 'Unknown entity:',
    assistApply: 'Apply change',
    assistApplied: 'Applied',
    assistAppliedToast: 'Change applied – ⌘Z to undo',
    assistPrivacy:
      'The current version and matching entities go to the AI from your Home Assistant. Nothing is saved without you.',
    disabledGroup: 'Disabled',
    aiButton: 'Create with AI',
    aiTitle: 'Create with AI',
    aiTitleScript: 'Create script with AI',
    aiIntro: 'Describe what should happen. The AI from your Home Assistant turns it into a draft.',
    aiIntroScript:
      'Describe what the script should do. The AI from your Home Assistant turns it into a draft.',
    aiDescribe: 'Description',
    aiExample1: 'When the front door opens after sunset, turn on the hallway light for 5 minutes',
    aiExample2: 'On weekdays at 6:30, slowly brighten the living room light',
    aiExample3: 'Notify me when the washing machine is done',
    aiExampleScript1: 'Good-morning script: light at a chosen brightness, then open the blinds',
    aiExampleScript2: 'All off: turn off every light and media player, lock the front door',
    aiExampleScript3: 'Timer script: turn on the coffee maker for a chosen number of minutes',
    aiCreate: 'Create draft',
    aiRunning: 'AI is building the flow …',
    aiPrivacy:
      'Just a draft – nothing is saved until you save. Your description and names/IDs of matching entities go to the AI you set up in Home Assistant.',
    aiUnknown: "Draft created, but these entities don't exist: ",
    aiDone: 'Draft created – review it, then save',
    aiSetupTitle: 'Build automations with AI',
    aiSetupText:
      'FLODE uses the AI you set up in Home Assistant (an integration with “AI Task”, e.g. OpenAI, Anthropic, Google or Ollama). Then pick it under Settings → System → AI → “AI suggestions” → “Data generation tasks”.',
    aiSetupDefault:
      'You already have an AI with “AI Task”, but none is chosen as default for data generation. Pick it under Settings → System → AI → “AI suggestions”.',
    aiOpenIntegrations: 'Open devices & services',
    aiOpenDefault: 'Choose AI',
    aiDismiss: 'Hide hint',
    aiExplain: 'Explain run',
    aiExplaining: 'AI is reading the run …',
    aiExplainAgain: 'Explain again',
    cancel: 'Cancel',
    runs: 'Runs',
    refresh: 'Reload',
    noRuns: 'No runs yet – trigger the automation once.',
    runsHint: 'Home Assistant only keeps the last runs per automation (default: 5).',
    timeline: 'Timeline',
    stepDetails: 'Step',
    pickStep: 'Click a step in the timeline to see its details.',
    run_running: 'Running',
    run_finished: 'Finished',
    run_failed_conditions: 'Condition not met',
    run_error: 'Error',
    run_aborted: 'Aborted',
    run_other: 'Stopped',
    lastRun: 'Last run',
    showRuns: 'Show runs',
    addNext: 'Add action (after this)',
    addFirstTrigger: 'Add trigger',
    addFirstAction: 'Add action',
    emptyScriptHint: 'What should the script do?',
    entry: 'Start',
    fields: 'Fields',
    emptyHint: 'What should start the automation?',
    newScript: 'New script',
    automations: 'Automations',
    scripts: 'Scripts',
    run: 'Run (saved version)',
    runNeedsSave: 'Save first, then run',
    rename: 'Rename',
    tabsLabel: 'Open automations',
    newTab: 'New automation in a new tab',
    closeTab: 'Close tab',
    tidy: 'Tidy up',
    tidied: 'Tidied up – ⌘Z to undo',
    mode: 'Mode',
    mode_single: 'Single',
    mode_restart: 'Restart',
    mode_queued: 'Queued',
    mode_parallel: 'Parallel',
    resize: 'Drag to resize · double-click = default',
    homeHint:
      'Build, test and understand automations and scripts as flows – saved as plain Home Assistant YAML.',
    loadFailed: 'Could not be loaded',
    saveFailed: 'Saving failed',
    invalid: 'Invalid',
    type_trigger: 'Trigger',
    type_automation: 'Automation',
    type_script: 'Script',
    type_condition: 'Condition',
    type_action: 'Action',
    type_delay: 'Delay',
    type_wait: 'Wait',
    type_set_variables: 'Variables',
  },
} as const;

export type StringKey = keyof (typeof STRINGS)['en'];

export function t(language: string, key: StringKey): string {
  const table = language.startsWith('de') ? STRINGS.de : STRINGS.en;
  return table[key];
}
